export const site = {
  name: "Strategic Machines",
  product: "The Accelerator",
  tagline: "You manage your website. AI delivers the outcome.",
  /** The hero's cycling verb: "You [manage] your website." First word is the static one. */
  verbs: ["manage", "design", "change", "validate", "inspect", "approve", "release", "govern", "improve"],
  eyebrow: "The AI Control Room for your website",
  subline: "From requirement to release, every action is controlled, tested, and backed by evidence.",
  description:
    "The Control Room for designing, building, testing, and releasing your website with AI. You direct; AI designs, builds, tests, and deploys, with evidence for every change.",
  domain: "strategicmachines.ai",
  url: "https://strategicmachines.ai",
  waitlistCtaLabel: "Commission your app",
} as const;

/**
 * Brand imagery. The logo is the 512×512 master icon on Cloudinary, resized
 * by URL transformation; the social card is generated by app/og/route.tsx.
 * - logoNav: 96px (3× the 32px it renders at), auto format/quality.
 * - logoCard: 144px PNG for the social card (the card renderer needs PNG/JPEG).
 */
const CLOUDINARY = "https://res.cloudinary.com/stratmachine/image/upload";
const LOGO_ID = "v1592332363/machine/icon-512x512_zaffp5.png";

export const brand = {
  logo: `${CLOUDINARY}/${LOGO_ID}`,
  logoNav: `${CLOUDINARY}/w_96,h_96,c_fit,f_auto,q_auto/${LOGO_ID}`,
  logoCard: `${CLOUDINARY}/w_144,h_144,c_fit,f_png/${LOGO_ID}`,
  socialImage: {
    url: `${site.url}/og`,
    width: 1200,
    height: 630,
    alt: "Strategic Machines: You manage your website. AI delivers the outcome.",
  },
} as const;



export type NavItem = {
  label: string;
  href: string;
  /** Off-site destination: opens in a new tab (see components/marketing/nav-link.tsx). */
  external?: boolean;
};

export const blogUrl = "https://blog.strategicmachines.ai/";

export const primaryNav: NavItem[] = [
  { label: "Fit Scan", href: "/fit-scan" },
  { label: "The Accelerator", href: "/platform" },
  { label: "Commissioning", href: "/#commissioning" },
  { label: "Customer Zero", href: "/customers/cypress-resort" },
  { label: "Pricing", href: "/pricing" },
  { label: "Partners", href: "/partners" },
  { label: "Company", href: "/company" },
  { label: "Blog", href: blogUrl, external: true },
];

export const footerColumns: { title: string; items: NavItem[] }[] = [
  {
    title: "Product",
    items: [
      { label: "Fit Scan", href: "/fit-scan" },
      { label: "The Accelerator", href: "/platform" },
      { label: "Commissioning", href: "/#commissioning" },
      { label: "Evidence, not code review", href: "/#evidence" },
      { label: "Pricing", href: "/pricing" },
    ],
  },
  {
    title: "Company",
    items: [
      { label: "About", href: "/company" },
      { label: "Blog", href: blogUrl, external: true },
      { label: "Customer Zero", href: "/customers/cypress-resort" },
      { label: "Partner Program", href: "/partners" },
      { label: "Apply for commissioning", href: "/#waitlist" },
    ],
  },
  {
    title: "Legal",
    items: [
      { label: "Privacy", href: "/legal/privacy" },
      { label: "Terms", href: "/legal/terms" },
    ],
  },
];
